[tools]
flux2 = "2.7.3"
kubectl = "1.35.0"
kustomize = "5.7.0"
yq = "4.48.1"
kubeconform = "0.7.0"
pkl = "0.30.2"
hk = "1.28.0"
pipx = "latest"
yamllint = "latest"
shellcheck = "latest"
shfmt = "latest"

[settings]
lockfile = true

[hooks]
postinstall = "hk install --mise"

[tasks.pre-commit]
description = 'Run pre-commit hook'
run = "hk run pre-commit"

[tasks.pre-push]
description = 'Run pre-push hook'
run = "hk run pre-push"

[tasks.check]
description = 'Check current code using linters and formatters'
run = "hk check"

[tasks.fix]
description = 'Fix current code using linters and formatters'
run = "hk fix"
