[tools]
flux2 = "2.7.3"
kubectl = "1.35.0"
kustomize = "5.7.0"
yq = "4.48.1"
kubeconform = "0.7.0"
pkl = "0.30.2"
hk = "1.28.0"
pipx = "latest"
yamllint = "latest"
shellcheck = "latest"
shfmt = "latest"

[settings]
lockfile = true

[hooks]
postinstall = "hk install --mise"
