apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
resources:
  - ../base/podinfo
  - ../base/home-assistant
  - ../base/mosquitto
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
